services:
  mysql:
    image: mysql:latest
    container_name: database-container
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
  backend:
    build:
      context: ./app/backend
    container_name: backend-container
    depends_on:
      - mysql
      - redis
    ports:
      - "3000:3000"
    env_file:
      - .env

  frontend:
    build:
      context: ./app/frontend
    container_name: frontend-container
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      API_HOST: http://backend-container:3000
    depends_on:
      - backend

volumes:
  mysql-data:
  redis_data: