services:
  mysql:
    image: mysql:latest
    container_name: database-container
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
volumes:
  mysql-data:
  redis_data: