apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MTcxMjIzZGMwMGM1MzM5ZTZlNWY4ZmNkZjU4Y2EzYzc=
  MYSQL_USER: MTQyMjM4NzM=
  MYSQL_PASSWORD: ZTk3NDIxYjZmZTMzZjg5NThlZjY1MjU5YzE1OTk5NmI=
  DATABASE_URL: MTQyMjM4NzM6ZTk3NDIxYjZmZTMzZjg5NThlZjY1MjU5YzE1OTk5NmJAdGNwKG15c3FsOjMzMDYpL2RhdGFiYXNl
